apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
namePrefix: staging-
nameSuffix: "-001"

commonLabels:
  app: staging

resources:
  - ../../base

patchesStrategicMerge:
  - increase_replicas.yaml
  - set_memory.yaml
